name: money_manager
description: "A money expense tracker app"
publish_to: 'none'
version: 0.1.2

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  file_picker: ^7.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: 'assets/money_manager_icon.png'
  android: true
